### ISSUE TITLE
请教：如何修改kubelet的node-ip

### ISSUE THREAD

**Issue by muercy** [maguowei/kubernetes-for-china#13]
您好，每个node是多网卡的话，需要在kubelet启动参数中指定--node-ip，请教该如何操作

**Comment by maguowei** [comment]
这个或许有帮助：https://github.com/kubernetes/kubeadm/issues/203

**Comment by lidalao** [comment]
Hi,
在单主集群中，添加‘--node-ip’可以工作。但是在最新的多主集群方式中，新主节点的etcd服务仍然不会用指定的node ip。
重新步骤参考：https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/
环境： 
1. docker-ce: 
```
version 18.09.7, build 2d0083d
```
2.  k8s:v1.15.0, 
```
kubeadm version: &version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:41Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
3.  ubuntu v18.4 LTS. (VirtualBox)
