### ISSUE TITLE
Support 1.13.0

### ISSUE THREAD

**Issue by wizardbyron** [maguowei/kubernetes-for-china#8]
[ERROR KubeletVersion]: the kubelet version is higher than the control plane version. This is not a supported version skew and may lead to a malfunctional cluster. Kubelet version: "1.13.0" Control plane version: "1.12.2"

**Comment by wizardbyron** [comment]
I'll made a PR to fix it.

**Comment by wizardbyron** [comment]
https://github.com/maguowei/kubernetes-for-china/pull/9

**Comment by maguowei** [comment]
#9 https://github.com/maguowei/kubernetes-for-china/commit/40bd47e428c10105446d2db70acf78ab22070d61
